name: Test2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.6
      - run: julia registry add https://github.com/JuliaRegistries/GitHubActions.jl; instantiate
      - name: Install dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      - name: Test package
        run: julia --project=@. -e 'using Pkg; Pkg.test("Astrodynamics")'

