# This is a basic workflow to run all the unit tests with an action for every commit in the "main" branch

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "test"
  test:
  # The type of runner that the job will run on (also common: ubuntu-latest)
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          julia-version: ['1.8.3', '1', 'nightly'] 
          julia-arch: [x64, x86]
          os: [ubuntu-latest, windows-latest, macOS-latest]
          exclude:
            - os: macOS-latest
              julia-arch: x86
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2          # maybe edit to v3
        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}
        - uses: julia-actions/julia-buildpkg@v1
        - name: Install GitHubActions package
          run: julia -e 'import Pkg; Pkg.add("GitHubActions")'
        - uses: julia-actions/julia-runtest@v1
          with:
            annotate: true
